return {
	{
		"nvim-treesitter/nvim-treesitter",
		build = ":TSUpdate",
	},
	{
		"windwp/nvim-ts-autotag",
		event = "VeryLazy",
		config = function()
			require("nvim-ts-autotag").setup({
				filetypes = {
					"html",
					"javascript",
					"typescript",
					"javascriptreact",
					"typescriptreact",
					"svelte",
					"vue",
					"tsx",
					"jsx",
					"rescript",
					"xml",
					"php",
					"markdown",
					"glimmer",
					"handlebars",
					"hbs",
				},
			})

			require("nvim-treesitter.configs").setup({
				ensure_installed = {
					"javascript",
					"typescript",
					"python",
					"vue",
					"regex",
					"sql",
					"comment",
					"toml",
					"jsonc",
					"json5",
					"gomod",
					"gowork",
					"go",
					"json",
					"proto",
					"make",
					"graphql",
					"html",
					"svelte",
					"yaml",
					"markdown",
					"markdown_inline",
					"http",
					"gitignore",
					"bash",
					"fish",
					"rust",
					"scss",
					"css",
					"lua",
					"tsx",
					"prisma",
					"solidity",
					"php",
				},
				indent = {
					enable = true,
				},
				highlight = {
					enable = true,
					additional_vim_regex_highlighting = true,
				},
				auto_install = true,
				incremental_selection = {
					enable = true,
					keymaps = {
						init_selection = "<C-space>",
						node_incremental = "<C-space>",
						scope_incremental = false,
						node_decremental = "<bs>",
					},
				},
			})
		end,
	},
}
